name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: job1
    environment: dev
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job3:
    runs-on: ubuntu-latest
    needs: job2
    continue-on-error: true
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job4:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: qa
    needs: job3
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job5:
    runs-on: ubuntu-latest
    needs: job4
    continue-on-error: true
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real

  
