name: CI
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: dev
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job2:
    runs-on: ubuntu-latest
    continue-on-error: true
    environment: qa
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    continue-on-error: true
    environment: dev
    steps:
      - name: Run dev
        id: run_step
        run: |
          echo "Running job1"
          # Cambia esto por tu lógica real

  
